version: '3.8'

services:
  app:
    build: .
    ports:
    - "8081:8081"
    restart: on-failure
  nginx:
    build: ./project/nginx
    restart: always
    ports:
    - "80:80"
    - "443:443"
    volumes:
      - ./project/nginx:/etc/nginx/conf.d/:ro
      - ./project/certbot/www/:/var/www/certbot/:ro
      - ./project/certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
    - app
  certbot:
    image: certbot/certbot:latest
    volumes:
    - ./project/certbot/www/:/var/www/certbot/:rw
    - ./project/certbot/conf/:/etc/letsencrypt/:rw
